What is NumPy?
NumPy is a Python library that provides us to make scientifical computations.
It has functions that aloows us to work in  the domain of linear algebra fourier transform, and matrices.
ITt is prefered because it is a fast and easy way. It is very helpful especially in data science where resources and speed are very important.


First we have to import numpy as below and then we can use it.
We can import it under np alias.

In [5]:
import numpy as np

ar=([1,2,3,4,5])
print(ar)

[1, 2, 3, 4, 5]


DIMENSIONS IN ARRAYS:

0-D Arrays: They are scalars. Each value in an array is a 0-D array.  
1-D Arrays: These are the most used and basic array types. It has 0-D arrays as its elements.
2-D Arrays: They are generally used for matrix and tensor demonstration. It has 1-D arrays as its elements.
3-D Arrays: It has 2-D arrays as its elements.

NumPy arrays provide us to see how many dimension has an array as integer. We can use it as below: 

In [6]:
import numpy as np

x = np.array(10)
y = np.array([1, 2, 3, 4, 5])
z = np.array([[1, 2, 3], [4, 5, 6]])
w = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(x.ndim)
print(y.ndim)
print(z.ndim)
print(w.ndim)

0
1
2
3


Accessing Array Elements: 
First we have to know the indexes starts from 0 in arrays. To access an index we have to enter elements indexes as below.

In [9]:
# Lets print a 1-D arrays element
import numpy as np

ar= np.array([0,1,2,3,4,5])
print(ar[1])

1


#Lets print a 2-D arrays element 
import numpy as np

ar=np.array([[0,1,2],
             [3,4,5]])
print('3rd element on the 2nd row: ',ar[1,2])

In [17]:
#Lets print a 3-D arrays element
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


Negative Indexing: It aloows us to reach the element from the end. Last elements index is -1 and from right to left it goes like -1,-2,-3...

In [20]:
import numpy as np

ar=np.array([[1,2,3,4,5],
             [6,7,8,9,10]])
print('Last element from right at 2nd row is: ',ar[0,-1])
#We first enter the row and then when we enter '-1' it returns the last element of the chosen row.

Last element from right at 2nd row is:  5


Slicing Arrays: It allows us to take elements from a given index to another given index.
                We can use [start:end] for slicing.
                We can also define the step like [start:end:step].
                If we don't pass step it it considered 1.
                If we don't pass end it is considered length of array in that dimension.
                If we don!t pass start it is considered 0.
                !! Start index is included but end index is not!!

In [ ]:
import numpy as np

ar1=np.array([1,2,3,4,5,6,7,8,9])
print(ar1[2:5])

ar2=np.array([1,2,3,4,5,6,7,8,9])
print(ar2[2:])

ar3=np.array([1,2,3,4,5,6,7,8,9])
print(ar3[:5])

ar4=np.array(['a','b','c','d','e','f','g','h'])
print(ar4[1:7:2])

ar5=np.array([1,2,3,4,5,6,7,8,9])
print(ar5[::2])
#It prints every second element starting from index 0.

ar6=np.array([1,2,3,4,5,6,7,8,9])
print(ar6[-5:-2])

ar7 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])
print(ar7[1:, 2:])




In [6]:
#Data Types 
import numpy as np

ar1 = np.array([1,2,3,4])
print(ar1.dtype)

ar2 = np.array(['apple','banana','cantaloupe'])
print(ar2.dtype)

#We can create arrays with defined data types.

import numpy as np

ar3 = np.array([1.1, 2.2, 3.3, 4.4],dtype='int64')
print(ar3)
print(ar3.dtype)

#For i, u, f, S and U we can define size as well.

ar4 = np.array([1.1, 2.2, 3.3, 4.4],dtype='f4')
print(ar4)
print(ar4.dtype)

#Converting Data Type on Existing Arrays

ar5 = np.array([3.3, 4.4, 5.5])
newar=ar5.astype('i')
print(newar)
print(newar.dtype)

ar6 = np.array([0,1,2,-12])
newar2=ar6.astype('bool')
print(newar2)
print(newar2.dtype)     #It only gives false if number is zero.



int32
<U10
[1 2 3 4]
int64
[1.1 2.2 3.3 4.4]
float32
[3 4 5]
int32
[False  True  True  True]
bool


In [9]:
# Copy and View
# The main difference is between copy and view is copy is a new array and view just gets reference of another array. 
# Copy owns the data and if we make changes on copy it will not affect the original array.
# View doesn't own the data and if we make changes on view it will affect the original array.
import numpy as np

ar = np.array([1,2,3,4,5])
x=ar.copy()
x[2]=0
print(ar)
print(x)
y=ar.view()
y[2]=9
print(ar)
print(x)
print(y)

#Checking if Array Owns Its Data
# If copied it will return 'none' because it isn't referenced any other array 
# If viewed it will return the array which getting referenced

ar2 = np.array([1,2,3,4,5,6,7])
a=ar2.copy()
b=ar2.view()
print(a.base)
print(b.base)

[1 2 3 4 5]
[1 2 0 4 5]
[1 2 9 4 5]
[1 2 0 4 5]
[1 2 9 4 5]
None
[1 2 3 4 5 6 7]


In [15]:
# Shape of an array

import numpy as np

ar1=np.array([1,2,3,4,5,6,7])
print(ar1.shape)

ar2=np.array([[1,2,3,4],[5,6,7,8]])
print(ar2.shape)

ar3=np.array([1,2,3,4,5],ndmin=6)
print(ar3.shape)


(7,)
(2, 4)
(1, 1, 1, 1, 1, 5)


In [29]:
# Reshaping Arrays

import numpy as np
ar1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newar1 = ar1.reshape(4,3)
print(newar1)

print(          )

newar2 = ar1.reshape(2,3,2) 
#burada ilk değer kaç arrayden oluştuğunu gösteriyor, 2. değer her arrayin satır sayısı, 3. değer her arrayin sütun sayısı
print(newar2)

print(           )
#Returns are views
print(ar1.reshape(3,4).base)

print(          )
# Unknown Dimension - You don't have to specify the exact number to reshape

newar3=ar1.reshape(2,3,-1)
print(newar3)

print(            )
# Flattening the Arrays
ar2=np.array([[1,2,3,4],[5,6,7,8]])
x=ar2.reshape(-1)
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

[1 2 3 4 5 6 7 8]


In [30]:
op_dtypes????????????????

SyntaxError: invalid syntax (4244084886.py, line 1)

In [37]:
# Joining Arrays

import numpy as np

ar1 = np.array([1,2,3])
ar2 = np.array([4,5,6])
arr = np.stack((ar1,ar2))
print(arr)

[[1 2 3]
 [4 5 6]]
